import Link from "next/link";
import { MessageBanner } from "@/components/message-banner";
import { requireAdminMfa } from "@/lib/auth/identity";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { changeRate, reviewListing, reviewListingRevision, reviewOwner, suspendListing } from "./inventory-actions";

type PageProps = { searchParams: Promise<{ message?: string; error?: string }> };
type Verification = { owner_id: string; legal_name: string; business_type: string | null; status: string; submitted_at: string | null; document_asset_ids: string[] };
type Listing = { id: string; owner_id: string; title: string; category: string; status: string; locality: string; district: string; owner_base_rate_paise: number; rate_unit: string; ad_duration_seconds: number; plays_per_unit: number; operating_start: string; operating_end: string; service_promise: string; category_details: Record<string, unknown> };
type ListingRevision = { id: string; listing_id: string; version: number; payload: Record<string, unknown>; submitted_at: string };
function money(paise: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(paise / 100); }

export default async function AdminPage({ searchParams }: PageProps) {
  const [identity, query] = await Promise.all([requireAdminMfa(), searchParams]);
  const supabase = await createServerSupabaseClient();
  const [{ data: verifications, error: verificationError }, { data: submitted, error: submissionError }, { data: published, error: publishedError }, { data: submittedRevisions, error: revisionsError }, { count: bookingCount, error: bookingError }, { count: refundCount, error: refundError }, { count: supportCount, error: supportError }, { count: exceptionCount, error: exceptionError }] = await Promise.all([
    supabase.from("owner_verifications").select("owner_id,legal_name,business_type,status,submitted_at,document_asset_ids").eq("status","submitted").order("submitted_at"),
    supabase.from("inventory_listings").select("id,owner_id,title,category,status,locality,district,owner_base_rate_paise,rate_unit,ad_duration_seconds,plays_per_unit,operating_start,operating_end,service_promise,category_details").eq("status","submitted").order("submitted_at"),
    supabase.from("inventory_listings").select("id,owner_id,title,category,status,locality,district,owner_base_rate_paise,rate_unit,ad_duration_seconds,plays_per_unit,operating_start,operating_end,service_promise,category_details").eq("status","published").order("published_at", { ascending: false }),
    supabase.from("inventory_listing_revisions").select("id,listing_id,version,payload,submitted_at").eq("status", "submitted").order("submitted_at"),
    supabase.from("booking_lines").select("id", { count: "exact", head: true }).eq("status", "paid_pending"),
    supabase.from("refund_obligations").select("id", { count: "exact", head: true }).eq("status", "pending_manual"),
    supabase.from("support_tickets").select("id", { count: "exact", head: true }).in("status", ["open", "in_progress"]),
    supabase.from("payment_exceptions").select("provider_payment_id", { count: "exact", head: true }).eq("status", "pending_manual")
  ]);
  if (verificationError || submissionError || publishedError || revisionsError || bookingError || refundError || supportError || exceptionError) throw new Error("Admin workspace records could not be loaded.");
  const ownerQueue = (verifications ?? []) as Verification[];
  const listingQueue = (submitted ?? []) as Listing[];
  const live = (published ?? []) as Listing[];
  const revisionQueue = (submittedRevisions ?? []) as ListingRevision[];
  return <main className="dashboard-shell wide-dashboard">
    <div className="dashboard-heading"><div><span className="eyebrow">AAL2 protected</span><h1>Inventory control room</h1><p>{identity.fullName}, verify owners, approve service promises and control every published rate.</p></div><div className="heading-actions"><Link className="button button-secondary button-small" href="/admin/bookings">Booking review</Link><Link className="button button-secondary button-small" href="/admin/support">Support queue</Link><span className="status status-ok">Admin MFA verified</span></div></div>
    <MessageBanner message={query.message} error={query.error} />
    <section className="admin-section"><div className="section-heading compact-heading"><div><span className="eyebrow">Operational queues</span><h2>Work requiring follow-up</h2></div><p>Counts come from current records; pending refunds and exceptions do not mean money has moved.</p></div><div className="metric-grid admin-operation-metrics"><Link href="/admin/bookings"><span>Booking decisions</span><strong>{bookingCount ?? 0}</strong><small>Paid requests awaiting admin</small></Link><Link href="/admin/refunds"><span>Manual refunds</span><strong>{refundCount ?? 0}</strong><small>Pending obligations</small></Link><Link href="/admin/support?status=active"><span>Active support</span><strong>{supportCount ?? 0}</strong><small>Open or in progress</small></Link><Link href="/admin/refunds"><span>Payment exceptions</span><strong>{exceptionCount ?? 0}</strong><small>Pending reconciliation</small></Link></div></section>
    <div className="metric-grid"><div><span>Owner reviews</span><strong>{ownerQueue.length}</strong><small>Submitted identities</small></div><div><span>Listing reviews</span><strong>{listingQueue.length + revisionQueue.length}</strong><small>Initial and replacement submissions</small></div><div><span>Published</span><strong>{live.length}</strong><small>Public read API records</small></div></div>
    <section className="admin-section"><div className="section-heading compact-heading"><div><span className="eyebrow">Queue 01</span><h2>Owner verification</h2></div><p>Documents are private. Download links expire after five minutes.</p></div>
      {ownerQueue.length ? <div className="admin-review-grid">{ownerQueue.map((owner) => <article className="panel-card review-card" key={owner.owner_id}><div className="panel-title"><div><span className="inventory-kicker">{owner.business_type || "Owner"}</span><h2>{owner.legal_name}</h2></div><span className="status status-warning">submitted</span></div><div className="document-links">{owner.document_asset_ids.map((id,index) => <a key={id} href={`/api/media/${id}/download`} target="_blank" rel="noreferrer">Document {index+1} ↗</a>)}</div><form action={reviewOwner} className="form-stack compact-review"><input type="hidden" name="ownerId" value={owner.owner_id} /><label>Decision reason<textarea name="reason" rows={2} placeholder="Required for rejection or suspension" /></label><div className="review-actions"><button className="button button-small" name="decision" value="approved">Approve owner</button><button className="button button-secondary button-small danger-button" name="decision" value="rejected">Reject</button></div></form></article>)}</div> : <p className="queue-empty">No owner verification awaiting review.</p>}
    </section>
    <section className="admin-section"><div className="section-heading compact-heading"><div><span className="eyebrow">Queue 02</span><h2>Listing publication</h2></div><p>Approve the initial owner rate, service promise, capacity and location together.</p></div>
      {listingQueue.length ? <div className="admin-review-grid">{listingQueue.map((listing) => <article className="panel-card review-card" key={listing.id}><div className="panel-title"><div><span className="inventory-kicker">{listing.category} · {listing.locality}, {listing.district}</span><h2>{listing.title}</h2></div><b>{money(listing.owner_base_rate_paise)} / {listing.rate_unit.replaceAll("_"," ")}</b></div><dl className="spec-grid"><div><dt>Duration</dt><dd>{listing.ad_duration_seconds}s</dd></div><div><dt>Plays</dt><dd>{listing.plays_per_unit}</dd></div><div><dt>Hours</dt><dd>{listing.operating_start.slice(0,5)}–{listing.operating_end.slice(0,5)}</dd></div></dl><p>{listing.service_promise}</p><details><summary>Category details</summary><pre>{JSON.stringify(listing.category_details,null,2)}</pre></details><form action={reviewListing} className="form-stack compact-review"><input type="hidden" name="listingId" value={listing.id} /><label>Review reason<textarea name="reason" rows={2} placeholder="Required for rejection" /></label><div className="review-actions"><button className="button button-small" name="decision" value="published">Publish listing</button><button className="button button-secondary button-small danger-button" name="decision" value="rejected">Reject</button></div></form></article>)}</div> : <p className="queue-empty">No listing awaiting publication.</p>}
    </section>
    <section className="admin-section"><div className="section-heading compact-heading"><div><span className="eyebrow">Queue 03</span><h2>Published listing replacements</h2></div><p>The current approved listing remains public until a replacement is accepted. Published rates stay under the separate admin rate workflow.</p></div>
      {revisionQueue.length ? <div className="admin-review-grid">{revisionQueue.map((revision) => { const payload = revision.payload; const details = (payload.categoryDetails ?? {}) as Record<string, unknown>; return <article className="panel-card review-card" key={revision.id}><div className="panel-title"><div><span className="inventory-kicker">Replacement v{revision.version} · {String(payload.category)}</span><h2>{String(payload.title)}</h2></div><span className="status status-warning">submitted</span></div><dl className="spec-grid"><div><dt>Location</dt><dd>{String(payload.locality)}, {String(payload.district)}</dd></div><div><dt>Duration</dt><dd>{String(payload.adDurationSeconds)}s</dd></div><div><dt>Plays</dt><dd>{String(payload.playsPerUnit)}</dd></div><div><dt>Hours</dt><dd>{String(payload.operatingStart)}–{String(payload.operatingEnd)}</dd></div></dl><p>{String(payload.servicePromise)}</p>{Array.isArray(payload.blackouts) ? <div className="review-blackouts"><strong>Proposed unavailable / self-use dates</strong>{payload.blackouts.length ? <ul>{payload.blackouts.map((item, index) => { const block = item as Record<string, unknown>; return <li key={index}>{String(block.startsOn)} to {String(block.endsOn)} — {String(block.reason)}</li>; })}</ul> : <p>None requested; approval will clear existing unavailable dates.</p>}</div> : null}<details><summary>Replacement details</summary><pre>{JSON.stringify(details, null, 2)}</pre></details><form action={reviewListingRevision} className="form-stack compact-review"><input type="hidden" name="revisionId" value={revision.id} /><label>Review reason<textarea name="reason" rows={2} placeholder="Required for rejection" /></label><div className="review-actions"><button className="button button-small" name="decision" value="approved">Publish replacement</button><button className="button button-secondary button-small danger-button" name="decision" value="rejected">Request changes</button></div></form></article>; })}</div> : <p className="queue-empty">No replacement revisions awaiting review.</p>}
    </section>
    <section className="admin-section"><div className="section-heading compact-heading"><div><span className="eyebrow">Published inventory</span><h2>Rates and suspensions</h2></div><p>Only admin can change a live rate, after recording the owner discussion.</p></div>
      {live.length ? <div className="published-admin-list">{live.map((listing) => <article className="panel-card live-row" key={listing.id}><div><span className="inventory-kicker">{listing.category} · {listing.locality}</span><h2>{listing.title}</h2><p>Current rate <b>{money(listing.owner_base_rate_paise)}</b> / {listing.rate_unit.replaceAll("_"," ")}</p></div><form action={changeRate} className="rate-form"><input type="hidden" name="listingId" value={listing.id} /><label>New rate ₹<input name="rateRupees" type="number" min="100" step="0.01" required /></label><label>Owner discussion<input name="discussionNote" minLength={10} required /></label><label>Reason<input name="reason" minLength={5} required /></label><button className="button button-small">Publish new rate</button></form><form action={suspendListing} className="suspend-form"><input type="hidden" name="listingId" value={listing.id} /><input name="reason" minLength={5} required placeholder="Suspension reason" /><button className="button button-secondary button-small danger-button">Suspend</button></form></article>)}</div> : <p className="queue-empty">No published inventory.</p>}
    </section>
  </main>;
}
