"use client";

import { useState } from "react";
import { createListing, updateListing } from "@/app/owner/actions";
import { LocationPicker } from "@/components/location-picker";

type InitialListing = Record<string, string | number | boolean | string[] | undefined> & { id?: string; category?: "led" | "theatre" | "mobile" };
export function ListingForm({ initial }: { initial?: InitialListing }) {
  const [category, setCategory] = useState<"led" | "theatre" | "mobile">(initial?.category ?? "led");
  const value = (key: string) => initial?.[key] as string | number | undefined;
  return <form action={initial?.id ? updateListing : createListing} className="listing-form form-stack">
    {initial?.id ? <input type="hidden" name="listingId" value={initial.id} /> : null}
    <section className="panel-card form-section">
      <span className="eyebrow">1 · Format</span><h2>Choose the inventory model</h2>
      <div className="category-choice">{(["led", "theatre", "mobile"] as const).map((value) => <label key={value} className={category === value ? "selected" : ""}><input type="radio" name="category" value={value} checked={category === value} disabled={Boolean(initial?.id) && value !== category} onChange={() => { if (!initial?.id) setCategory(value); }} /><b>{value === "led" ? "LED / digital" : value === "theatre" ? "Theatre shows" : "Mobile billboard"}</b><small>{value === "led" ? "One advertiser per whole day" : value === "theatre" ? "Multiple slots per show" : "Rotating slots on a vehicle"}</small></label>)}</div>
    </section>
    <section className="panel-card form-section"><span className="eyebrow">2 · Listing</span><h2>Public information</h2>
      <label>Listing title<input name="title" required minLength={3} maxLength={120} placeholder="MG Road digital screen" defaultValue={value("title")} /></label>
      <label>Description<textarea name="description" required minLength={20} maxLength={2000} rows={4} placeholder="Describe the placement without promising unverified reach or availability." defaultValue={value("description")} /></label>
      <LocationPicker initial={initial ? { provider: value("sourceProvider") as "mappls"|"google"|"manual", placeId: String(value("sourcePlaceId") ?? ""), label: String(value("locality") ?? ""), locality: String(value("locality") ?? ""), district: String(value("district") ?? ""), latitude: Number(value("latitude")), longitude: Number(value("longitude")) } : undefined} />
      <div className="field-row"><label>Owner audience estimate<input name="audienceEstimate" type="number" min="1" required defaultValue={value("audienceEstimate")} /></label><label>Estimate basis<input name="audienceBasis" required minLength={10} placeholder="Method, source and date" defaultValue={value("audienceBasis")} /></label></div>
    </section>
    <section className="panel-card form-section"><span className="eyebrow">3 · Service</span><h2>Promise and capacity</h2>
      <div className="field-row three-fields"><label>Ad duration (seconds)<input name="adDurationSeconds" type="number" min="5" max="120" required defaultValue={value("adDurationSeconds")} /></label><label>Plays per {category === "theatre" ? "show" : "day"}<input name="playsPerUnit" type="number" min="1" max="2000" required defaultValue={value("playsPerUnit")} /></label><label>Base rate (₹ / {category === "led" ? "day" : "slot"})<input name="baseRateRupees" type="number" min="100" step="0.01" required defaultValue={value("baseRateRupees")} /></label></div>
      <div className="field-row"><label>Operating start<input name="operatingStart" type="time" required defaultValue={value("operatingStart")} /></label><label>Operating end<input name="operatingEnd" type="time" required defaultValue={value("operatingEnd")} /></label></div>
      <label>Owner service promise<textarea name="servicePromise" required minLength={20} rows={3} placeholder="State exactly what will be delivered and evidenced." defaultValue={value("servicePromise")} /></label>
      {category === "led" ? <div className="category-details"><div className="field-row three-fields"><label>Creative width (px)<input name="screenWidthPx" type="number" min="320" required defaultValue={value("screenWidthPx")} /></label><label>Creative height (px)<input name="screenHeightPx" type="number" min="240" required defaultValue={value("screenHeightPx")} /></label><label>Daily capacity<input value="1 — whole screen" readOnly /></label></div><div className="field-row"><label>Physical width (m)<input name="physicalWidthMetres" type="number" step="0.1" min="0.1" required defaultValue={value("physicalWidthMetres")} /></label><label>Physical height (m)<input name="physicalHeightMetres" type="number" step="0.1" min="0.1" required defaultValue={value("physicalHeightMetres")} /></label></div></div> : null}
      {category === "theatre" ? <div className="category-details"><div className="field-row three-fields"><label>Venue<input name="venueName" required defaultValue={value("venueName")} /></label><label>Auditorium<input name="auditoriumName" required defaultValue={value("auditoriumName")} /></label><label>Slots per show<input name="slotsPerShow" type="number" min="1" max="50" required defaultValue={value("slotsPerShow")} /></label></div><label>Upcoming show starts<textarea name="showStarts" rows={4} required placeholder={'One ISO instant per line, for example:\n2026-10-12T18:30:00+05:30'} defaultValue={Array.isArray(initial?.showStarts) ? initial.showStarts.join("\n") : value("showStarts")} /></label></div> : null}
      {category === "mobile" ? <div className="category-details"><div className="field-row"><label>Vehicle label<input name="vehicleLabel" required placeholder="Vehicle or fleet label" defaultValue={value("vehicleLabel")} /></label><label>Rotating slots<input name="rotatingSlots" type="number" min="1" max="30" required defaultValue={value("rotatingSlots")} /></label></div><label>Published route name<input name="routeName" required defaultValue={value("routeName")} /></label><label>Approved route geometry (GeoJSON LineString)<textarea name="routeGeoJson" rows={5} required placeholder={'{"type":"LineString","coordinates":[[76.27,9.97],[76.30,10.01]]}'} defaultValue={value("routeGeoJson")} /></label><label className="check"><input name="customRouteAllowed" type="checkbox" defaultChecked={Boolean(initial?.customRouteAllowed)} /> Owner permits custom-route requests when no approved booking overlaps the dates</label></div> : null}
      <label>Known blackout ranges<textarea name="blackouts" rows={3} placeholder={'Optional, one per line: 2026-10-20|2026-10-22|Maintenance'} defaultValue={value("blackouts")} /></label>
    </section>
    <div className="submission-bar"><div><b>Owner draft</b><small>Admin must approve the service terms and initial price before publication.</small></div><button className="button" type="submit">{initial?.id ? "Update listing draft" : "Save listing draft"}</button></div>
  </form>;
}
