import Link from "next/link";
import { MediaUpload } from "@/components/media-upload";
import { requireIdentity } from "@/lib/auth/identity";
import { createServerSupabaseClient } from "@/lib/supabase/server";

type Asset = { id: string; original_name: string; detected_mime: string; byte_size: number; pixel_width: number | null; pixel_height: number | null; scan_status: string; created_at: string };
export default async function CreativePage() {
  const identity = await requireIdentity();
  const { data } = await (await createServerSupabaseClient()).from("private_media_assets").select("id,original_name,detected_mime,byte_size,pixel_width,pixel_height,scan_status,created_at").eq("uploader_id",identity.userId).eq("purpose","creative").order("created_at", { ascending: false });
  const assets = (data ?? []) as Asset[];
  return <main className="dashboard-shell"><div className="dashboard-heading"><div><span className="eyebrow">Private media</span><h1>Creative library</h1><p>Files are never public. A booking later pins the exact validated version and checks it against that listing’s approved media rules.</p></div><Link className="button button-secondary button-small" href="/advertiser">Back</Link></div><section className="panel-card"><MediaUpload purpose="creative" inputName="creativeAssetId" accept="image/png,image/jpeg,video/mp4,video/webm" label="Creative file (50 MB maximum)" /><p className="small-note muted">Image dimensions are read from file content. Video resolution, duration and codec remain gated for the production media-probe worker before checkout.</p></section><section className="asset-list"><div className="section-heading compact-heading"><div><span className="eyebrow">Uploaded assets</span><h2>Private versions</h2></div></div>{assets.length ? assets.map((asset) => <article className="asset-row" key={asset.id}><div><b>{asset.original_name}</b><small>{asset.detected_mime} · {(asset.byte_size/1024/1024).toFixed(2)} MB{asset.pixel_width ? ` · ${asset.pixel_width}×${asset.pixel_height}` : ""}</small></div><span className={`status ${asset.scan_status === "clean" ? "status-ok" : "status-warning"}`}>{asset.scan_status}</span><div className="asset-actions"><a className="button button-secondary button-small" href={`/api/media/${asset.id}/preview`} target="_blank" rel="noreferrer">Safe preview</a><a className="button button-secondary button-small" href={`/api/media/${asset.id}/download`}>Download</a></div></article>) : <p className="queue-empty">No creatives uploaded yet. Uploads appear after this page is refreshed.</p>}</section></main>;
}
