import Link from "next/link";
import { MessageBanner } from "@/components/message-banner";
import { requireAdminMfa } from "@/lib/auth/identity";
import { formatInr } from "@/lib/discovery/domain";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { addBookingNote, decideBooking } from "./actions";

type PageProps = { searchParams: Promise<{ message?: string; error?: string }> };
type Line = { id: string; cart_id: string; advertiser_id: string; category: string; status: string; paid_amount_paise: number; quantity: number; decision_due_at: string; listing_snapshot: { title?: string; locality?: string; district?: string }; service_snapshot: { servicePromise?: string; categoryDetails?: Record<string, unknown> }; creative_snapshot: { name?: string; assetId?: string; mime?: string; width?: number; height?: number }; request_configuration: { customRouteRequested?: boolean; requestedRoute?: unknown; routeName?: string }; service_windows: unknown };
type Note = { booking_line_id: string; body: string; created_at: string };

export default async function AdminBookingsPage({ searchParams }: PageProps) {
  const [, query] = await Promise.all([requireAdminMfa(), searchParams]);
  const supabase = await createServerSupabaseClient();
  const [{ data: lines }, { data: notes }, { count: refunds }] = await Promise.all([
    supabase.from("booking_lines").select("id,cart_id,advertiser_id,category,status,paid_amount_paise,quantity,decision_due_at,listing_snapshot,service_snapshot,creative_snapshot,request_configuration,service_windows").eq("status", "paid_pending").order("decision_due_at"),
    supabase.from("booking_admin_notes").select("booking_line_id,body,created_at").order("created_at"),
    supabase.from("refund_obligations").select("id", { count: "exact", head: true }).eq("status", "pending_manual"),
  ]);
  const queue = (lines ?? []) as Line[]; const allNotes = (notes ?? []) as Note[];
  return <main className="dashboard-shell wide-dashboard booking-page"><div className="dashboard-heading"><div><span className="eyebrow">AAL2 protected</span><h1>Paid request review</h1><p>Coordinate privately, then decide each line. Approval atomically allocates capacity; rejection creates manual refund work.</p></div><div className="heading-actions"><Link className="button button-secondary button-small" href="/admin">Inventory admin</Link><Link className="button button-secondary button-small" href="/admin/refunds">{refunds ?? 0} manual refunds</Link></div></div><MessageBanner message={query.message} error={query.error} />
    <div className="metric-grid"><div><span>Awaiting decisions</span><strong>{queue.length}</strong><small>Paid, still unreserved</small></div><div><span>Nearest deadline</span><strong>{queue[0] ? new Date(queue[0].decision_due_at).toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" }) : "—"}</strong><small>Exact time shown per line</small></div><div><span>Refund tasks</span><strong>{refunds ?? 0}</strong><small>No automatic money movement</small></div></div>
    {queue.length ? <div className="admin-review-grid booking-admin-grid">{queue.map((line) => <article className="panel-card review-card" key={line.id}><div className="panel-title"><div><span className="inventory-kicker">{line.category} · {line.listing_snapshot.locality}, {line.listing_snapshot.district}</span><h2>{line.listing_snapshot.title}</h2></div><b>{formatInr(line.paid_amount_paise)}</b></div><div className="banner banner-warning">Paid pending — capacity is not reserved.</div><dl className="spec-grid"><div><dt>Quantity</dt><dd>{line.quantity}</dd></div><div><dt>Creative</dt><dd>{line.creative_snapshot.name}</dd></div><div><dt>Due (IST)</dt><dd>{new Date(line.decision_due_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</dd></div></dl><details><summary>Frozen units and service</summary><pre>{JSON.stringify({ windows: line.service_windows, service: line.service_snapshot }, null, 2)}</pre></details>{line.creative_snapshot.assetId ? <a className="button button-secondary button-small" href={`/api/media/${line.creative_snapshot.assetId}/preview`} target="_blank" rel="noreferrer">Preview frozen creative</a> : null}{line.category === "mobile" ? <div className="route-review"><b>{line.request_configuration.customRouteRequested ? "Custom route requested" : "Published rotating route"}</b><pre>{JSON.stringify(line.request_configuration.requestedRoute, null, 2)}</pre></div> : null}
        <form action={addBookingNote} className="form-stack compact-review internal-note-box"><input type="hidden" name="lineId" value={line.id} /><label>Private coordination note<textarea name="note" minLength={2} maxLength={5000} rows={2} required /></label><button className="button button-secondary button-small">Add private note</button></form>{allNotes.filter((note) => note.booking_line_id === line.id).map((note) => <p className="admin-note" key={note.created_at}><b>Private:</b> {note.body}</p>)}
        <form action={decideBooking} className="form-stack compact-review"><input type="hidden" name="lineId" value={line.id} /><label>Decision reason<textarea name="reason" minLength={5} maxLength={1000} rows={2} required /></label>{line.category === "mobile" ? <label>Owner-agreed route GeoJSON<textarea name="agreedRoute" rows={5} defaultValue={JSON.stringify(line.request_configuration.requestedRoute)} required={line.request_configuration.customRouteRequested} /></label> : null}<div className="review-actions"><button className="button button-small" name="decision" value="approved">Approve and allocate</button><button className="button button-secondary button-small danger-button" name="decision" value="rejected">Reject for refund</button></div></form>
      </article>)}</div> : <p className="queue-empty">No paid requests await a decision.</p>}
  </main>;
}
